### ISSUE TITLE
com.unicorn.store.StreamLambdaHandler not found

### ISSUE THREAD

**Issue by pkkht** [aws-samples/aws-lambda-java-workshop#855]
Hi,
I am trying the workshop code and focusing only on the Unicorn store Spring part.

After setting up infra, I have run

./deploy.sh spring

This has deployed the components. And when invoking the prod api gateway url - getting this error:

Class not found: com.unicorn.store.StreamLambdaHandler: java.lang.ClassNotFoundException
java.lang.ClassNotFoundException: com.unicorn.store.StreamLambdaHandler
	at java.base/java.net.URLClassLoader.findClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Unknown Source)
	at java.base/java.lang.Class.forName(Unknown Source)

I cannot find this class in the repository. Can you please advise on this?

**Comment by deki** [comment]
Hi @pkkht,
sorry for the late response. This class is being created in Step 3: https://catalog.workshops.aws/java-on-aws-lambda/en-US/01-migration/java-container#change-3-add-a-streamlambdahandler-class

Let me know if you need something else.
